apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cloud-shell"
  namespace: "kubecube-system"
spec:
  replicas: 1
  selector:
    matchLabels:
      kubecube.io/app: "kubecube-cloud-shell"
  template:
    metadata:
      labels:
        kubecube.io/app: "kubecube-cloud-shell"
    spec:
      volumes:
        - hostPath:
            path: /etc/localtime
          name: localtime
      containers:
        - name: cloud-shell
          image: hub.c.163.com/kubecube/kubecube:cloudshell-0.0.1
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: "File"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
          resources:
            limits:
              cpu: "2"
              memory: 1G
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            exec:
              command:
                - /bin/ls
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/ls
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 120
      restartPolicy: "Always"
