apiVersion: apps/v1
kind: Deployment
metadata:
  name: webconsole
  namespace: kubecube-system
  labels:
    kubecube.io/app: kubecube-webconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      kubecube.io/app: kubecube-webconsole
  template:
    metadata:
      labels:
        kubecube.io/app: kubecube-webconsole
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: 56F0D8DB90241C6E
          name: kubecube-webconsole
          image: hub.c.163.com/kubecube/kubecube:webconsole-0.0.3
          ports:
            - containerPort: 9081