apiVersion: v1
kind: Service
metadata:
  name: webconsole-nodeport
  namespace: kubecube-system
spec:
  type: NodePort
  selector:
    kubecube.io/app: kubecube-webconsole
  ports:
    - name: http
      port: 9081
      targetPort: 9081
      nodePort: 30010